[package]
name = "arikedb"
deacription = "arikedb rust library"
license = "MIT"
homepage = "https://arikedb.com"
repository = "https://github.com/alejandroalfonsoyero/arikedb-rust"
authors = ["Alejandro <alejandroalfonso1994@gmail.com>"]
readme = "README.md"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = "*"
prost = "*"
tokio = {version = "*", features = ["full"]}
tokio-stream = "*"

[build-dependencies]
tonic-build = "0.11.0"
prost-build = "0.12.6"
